version: "3.9"
services:
  nginx:
    image: ghcr.io/flavioheleno/gossamer-server-nginx:latest
    build:
      context: .
      dockerfile: nginx.Dockerfile
    environment:
      - PHP_FPM=gossamer
    ports:
      - "80:80/tcp"
    restart: unless-stopped
    depends_on:
      - gossamer
    networks:
      - gossamer-network
  gossamer:
    image: ghcr.io/flavioheleno/gossamer-server-fpm:latest
    build:
      context: .
      dockerfile: gossamer.Dockerfile
      target: fpm
    secrets:
      - postgres-passwd
      - postgres-user
      - postgres-db
    volumes:
      - ./data/gossamer/:/var/www/html/local/
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - gossamer-network
  postgres:
    image: postgres:14.2-alpine3.15
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
      - POSTGRES_USER_FILE=/run/secrets/postgres-user
      - POSTGRES_DB_FILE=/run/secrets/postgres-db
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    secrets:
      - postgres-passwd
      - postgres-user
      - postgres-db
    restart: unless-stopped
    networks:
      - gossamer-network

secrets:
  postgres-passwd:
    file: ./secrets/postgres-passwd.txt
  postgres-user:
    file: ./secrets/postgres-user.txt
  postgres-db:
    file: ./secrets/postgres-db.txt

networks:
  gossamer-network:
